### ISSUE TITLE
Rate of spec_traffic

### ISSUE THREAD

**Issue by lmclarke** [luciensadi/AwakeMUD#167]
In spec_procs.c there's a fancy table for traffic echoes that print on a cycle. It's pretty cool, but the speed at which they come in - once every 10 seconds - is very spammy. 

I haven't been able to find where this can be changed. Searching for "traffic" with grep showed only spec_assign.cpp and spec_procs.cpp, which include the following, but not a way to slow this way, way down. At least, not in so far as I can tell.

The grep!
```
spec_assign.cpp:  SPECIAL(traffic);
spec_assign.cpp:      ASSIGNROOM(world[x].number, traffic);
spec_procs.cpp:SPECIAL(traffic)
```

How can I slow these down to about one every fifteen minutes? I noticed the other room procs are much slower - oceansounds and what not.

**Comment by lmclarke** [comment]
It's actually weirder than I thought once I tracked it by seconds.

```
Every 10 seconds for 3 pulses:
6:03:23 - A large, white GMC Bulldog van drives through here.
6:03:33 - A red Chrysler-Nissan Jackrabbit cruises by.
6:03:43 - A red Ford Americar cruises by.

Starts to slow down...
6:04:13 - A yellow Ford Americar cruises by.
6:05:13 - A white Chrysler-Nissan Jackrabbit cruises by.
6:06:23 - An orkish woman drives through here on her Harley Scorpion.

Back to every 10 seconds
6:09:13 - A blue Ford Americar cruises by.
6:09:23 - A white Mitsubishi Runabout drives by slowly.
```

**Comment by luciensadi** [comment]
It's on a random switch as well as a timer. The simplest way to slow it down is to increase the upper bound of the random in `spec_procs.cpp`;  change the 50 in `switch (number(1, 50)) {` to a larger number and you'll see fewer traffic messages on average. You can also slow down the traffic by increasing the amount of wait time between calls to `spec_update()`, but that will slow down all spec procs instead of just traffic.

**Comment by lmclarke** [comment]
Thanks a lot, and apologies for all the silly questions.
