### ISSUE TITLE
Load all new chars with a radio set to 8

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#22]
Having a radio set to 8 is critical to being able to communicate with the game. New characters should be auto-loaded with a radio set to 8, perhaps with a room along the way that tells them that the yellow text they've been seeing is coming from their radio. The goal is to prevent any player from leaving chargen without a radio.

**Comment by jalles76** [comment]
Excellent idea. All for it!

**Comment by JohnDonCowan** [comment]
I think it would make more sense for starting players to receive the radio after the tutorial is over, so that they're not inundated with a flood of "WTB", "WTS", "did someone say [Thunderfury, Blessed Blade of the Windseeker]", etc. Maybe some type of private communication device at start instead, in case they want to contact a friend or an admin?

**Comment by luciensadi** [comment]
I'm liking the idea of saving the radio-awarding for the end (will need to rejigger the shops a bit so people don't buy a second radio and get salty about the wasted money), but I don't think we need to add a private comms device. Unauthorized / tutorial newbies can't communicate on any in-character channels, and the out-of-character (OOC) and newbie global channels are usable without needing any special items.

**Comment by luciensadi** [comment]
Resolved in merge from fork.
