### ISSUE TITLE
Implement perception test against invis and imp_invis spells

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#262]
It is currently possible to be 100% invisible to anyone without the correct gear or abilities by using the correct force-1 spell. In canon, this is mitigated by letting people test perception against the spell to break it, which incentivizes higher force casting. This test should be implemented.

Criteria for test:

- Must be tied in with existing visibility checks like CAN_SEE
- Must only check once per spell
- Must persist for the duration of the spell, even through checker's logoff/logon
- Must allow NPCs to test against it as well

**Comment by vitalyo7** [comment]
I think, rather than checking once, it should check at TICK intervals, ie.

world : abilities_tick : test if still visible

* For all mobiles in the room, do a test invisibility level vs detection level + bonus/penalty
* Bonus/Penalty should depend whether the player did something to alert the mobiles in the room, if the player remain still, and npcs are not alert (or not guarding the area), then it should be harder to break invisibility.

Alternatively there should also be a test to break invisibility, every time a player does something while invisible.

It should be reworked with stealth mechanics somehow, and stealth skills. A skilled thief/assassin should be more successful with a invis spells than a regular mobile.

**Comment by luciensadi** [comment]
Spell resistance test rules (SR3 p183) indicate that no modifiers apply to these tests unless specifically noted, and Invis/ImpInvis don't have any modifiers listed. I also don't see anything that supports more than one test against a sustained indirect illusion spell, but then again the game designers weren't balancing around a world where it'd be realistic to be ImpInvis 24/7 with a sustaining focus. I could see a re-test being possible every in-game day or something.

One of the key things that nerfs ImpInvis in canon is that organized enemies tend to have a mage who can perceive, or if you're raiding a corp there are ultrasonic sensors and defensive emplacements etc. Adding the latter bits in would make it less of a win button vs NPCs.

**Comment by luciensadi** [comment]
Check is implemented, currently without re-tests.
