### ISSUE TITLE
'set' command broken for offline players

### ISSUE THREAD

**Issue by jalles76** [luciensadi/AwakeMUD#27]
The set command has a switch to modify stats of an offline player (act.wizard.cpp:3460).

set file Puppet Qui 6
A Male Human's qui set to 6.
Saved in file.

However, the value does not get committed to the DB.

**Comment by luciensadi** [comment]
First-pass fix of this bug is in the bugfixes branch. Notably, some fields are set in do_set() that are not saved in save_char(). The ideal / complete fix for this issue will be to have each individual set command execute a targeted DB update ('update pfiles set x=y') to avoid the overhead of writing and re-writing all the values that haven't changed.

**Comment by jalles76** [comment]
Yes, I've noticed the behavior of updating every row for a single change in console and thought it rather expensive.
