### ISSUE TITLE
Implement Thrown Weapons

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#283]
Except grenades, because they're not currently suited for use in a room-based game. Too easy to grief with.

**Comment by vitalyo7** [comment]
I think grenades should be added as well. Explosive damage should not impact players/vehicles that do not have PK enabled.

Also smoke/gas grenades/flashbang grenades could actually be pretty awesome addition.

**Comment by vitalyo7** [comment]
Could the grenades be codes with same restriction as AOE spells? Players being able to only throw grenades in the same room as the target, with some time delay (to aim). Rooms marked as peaceful would negate any affect from grenade (i.e. bars).

If you place a restriction to only throw in the same room, how would it be different fighting a tough NPC as opposed to your friend casting spells to assist in combat?

It would be awesome, if grenades could be used to initiate a combat. I.e. you prime grenade that will only be thrown when you enter a room. So you could enter a room with hostile npcs, and automatically throw the flashbang to initiate combat. That would be cool, wouldn't it?

**Comment by luciensadi** [comment]
AOE spells are also not implemented in the game since they're hard to balance and make non-griefy too. Throwing grenades in the same room would raise the question of why you're unharmed by the grenade, and would also be OP for clearing large stacks of enemies (shove everything in bod/armor, toss grenades into stack, get ¥¥¥).

Maybe if grenades were single-target it'd work, but at that point there's not much reason to use a grenade over any other weapon.

**Comment by vitalyo7** [comment]
There is already some distance rules that exist for combat, such as melee characters spending rounds to try and reach their target. If the target is not at close range, why should it not be possible to throw a grenade too? Enemies could see the grenade and try to dodge, which would make them avoid the grenade, but put a penalty to their dodge, possibly for one combat round.

Grenades could be used to buff/debuff enemies, which would give more options in combat.  I mean spells kind of do that thing already, this would be just an addition.

With regard to them being OP, I am not sure if this would be different from maxing (bod/armor) and boosting oneself with spells from a friendly mage. That sounds like something that would also result in players steamrolling the npcs for profit.

I think the overall combat system needs to be rethought for the MUD. The buffs from spells, as well as gear need to have drawbacks, or there should be a way for npcs to negate those benefits in combat. So that the players are not invincible gods.

**Comment by luciensadi** [comment]
Distance rules for melee have a really wonky implementation-- you're out of range until you succeed at a test to close the distance, and then you're in range. There's no tracking of actual distance involved, and it ignores the size of the room you're in.

The essential problem with SR3 is that it wasn't designed to scale as high as we make it scale. It's an open-ended system that was probably only playtested at low and mid levels, and the DM was expected to rein in players before they got too powerful. I'm definitely in favor of figuring out how to tame the system for end-game players since it's so broken. Let me know what your thoughts are on how combat could be revamped.
